controller_list:
  - name: /mara/limb/left
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
  - name: /mara/limb/right
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
  - name: fake_left_end_effector_controller
    joints:
      - left_joint6
  - name: fake_right_end_effector_controller
    joints:
      - right_joint6